algoritmo "calculador"
var
      N1, N2 : Inteiro
      nome: Caractere
      operacao: Caractere
inicio
  Escreval ("----------------------------------")
  Escreval ("  CLASE DE LA PROFESORA CAROLINE  ")
  Escreval ("----------------------------------")
  Escreva  ("Informe seu nome")
  Leia(nome)
  Escreva ("Informe um número: ")
  Leia (N1)
  Escreva ("Informe outro número: ")
  Leia(N2)
  Escolha operacao


fimalgoritmo
